### ISSUE TITLE
The uploaded file isn't a valid NuGet package

### ISSUE THREAD

**Issue by ravpacheco** [OctopusDeploy/gulp-octo#1]
Hello guys,

I'm trying use gulp-octo to pack and push my node.js site to octopus but with error:
I'm also following this docs:
http://docs.octopusdeploy.com/pages/viewpage.action?pageId=3049551

"The uploaded file isn't a valid NuGet package. (400)"

I have also a log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'publish' ]
2 info using npm@2.14.7
3 info using node@v4.2.2
4 verbose run-script [ 'prepublish', 'publish', 'postpublish' ]
5 info prepublish octofxjs@0.0.10
6 info publish octofxjs@0.0.10
7 verbose unsafe-perm in lifecycle true
8 info octofxjs@0.0.10 Failed to exec publish script
9 verbose stack Error: octofxjs@0.0.10 publish: `node ./node_modules/gulp/bin/gulp.js publish`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid octofxjs@0.0.10
11 verbose cwd C:\Users\rafaelpa\Desktop\octofxjs
12 error Windows_NT 10.0.10240
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "publish"
14 error node v4.2.2
15 error npm  v2.14.7
16 error code ELIFECYCLE
17 error octofxjs@0.0.10 publish: `node ./node_modules/gulp/bin/gulp.js publish`
17 error Exit status 1
18 error Failed at the octofxjs@0.0.10 publish script 'node ./node_modules/gulp/bin/gulp.js publish'.
18 error This is most likely a problem with the octofxjs package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node ./node_modules/gulp/bin/gulp.js publish
18 error You can get their info via:
18 error     npm owner ls octofxjs
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

Is expected that gulp-octo wrapper my files as a Nuget package ?
Thanks

**Comment by thiagopxp** [comment]
I'm also experience the same issue:

http://i.imgur.com/8EdrHFH.jpg (error on running 'gulp publish')

npm: 3.7.5
@octopusdeploy/octopackjs: "0.0.5"
ocotopus server: 3.2.24

**Comment by zentron** [comment]
Just to confirm, as noted in the [documentation](http://docs.octopusdeploy.com/display/OD/Supported+Packages) and [guide](http://docs.octopusdeploy.com/display/OD/Node+on+*Nix+deployments), the non NuGet packaging feature is only available from Octopus Deploy 3.3 onwards. This release is currently in beta but we anticipate a RTW release within next few days.
