### ISSUE TITLE
Npm audit reports Prototype Pollution vulnerability

### ISSUE THREAD

**Issue by mjarosie** [OctopusDeploy/gulp-octo#12]
The vulnerability is introduced because of dependency on @octopusdeploy/octopackjs@0.0.7 which in turn depends on lodash@3.10.1

partial output of `npm audit`:
```Package         lodash
Patched in      >=4.17.5
Dependency of   @octopusdeploy/gulp-octo [dev]
Path            @octopusdeploy/gulp-octo > @octopusdeploy/octopackjs >
                  zip-stream > archiver-utils > lodash
```

Snyk report:
https://snyk.io/test/npm/@octopusdeploy/gulp-octo

As snyk suggests, the remedy would be to upgrade @octopusdeploy/octopackjs dependency to version 0.1.0.

**Comment by CNname** [comment]
There seems to multiple Moderate and Low level vulnerabilities regarding Lodash. Any chance you could update the Lodash dependencies?

**Comment by zentron** [comment]
Have updated gulp dependencies and npm audit looks clean (as of time of writing)
