### ISSUE TITLE
gulp-util - Deprecation

### ISSUE THREAD

**Issue by NishantRanjan** [OctopusDeploy/gulp-octo#13]
Its showing issue with Gulp-util, refer below url, will there be any update to this?

https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

**Comment by NishantRanjan** [comment]
Hi team
Any update on this issue?

gulp-util has been deprecated.

The README.md lists alternatives for all the components so a simple replacement should be enough.

Your package is popular but still relying on gulp-util, it would be good to publish a fixed version to npm as soon as possible.

See:

https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
gulpjs/gulp-util#143

**Comment by johnsimons** [comment]
This has been fixed as part of https://github.com/OctopusDeploy/gulp-octo/commit/3be7e7f319de296104618188be1a1b3ad2deeac9
