### ISSUE TITLE
Add to npm

### ISSUE THREAD

**Issue by grofit** [OctopusDeploy/gulp-octo#3]
Is there any chance you could do an `npm publish` so it is available via npm as it doesnt seem to be there currently.

You probably want to change the name to just `gulp-octo` not `@octopusdeploy/gulp-octo` as its pretty verbose when including it and does not really follow the normal npm convention.

== Update ==

Sorry turns out it is on there but its with the fully qualified name including scope, which I would still say is a little ghastly and could be shortened to just be available without the explicit scoping.

**Comment by SeanKilleen** [comment]
Just dropped by here and happened to see this.

FYI, on [one of the docs pages](http://docs.octopusdeploy.com/pages/viewpage.action?pageId=3049551), there's an explanation for this:

> To avoid confusion with the myriad of other "octo" themed npm packages and to provide guidance on those supported directly by Octopus Deploy, we have decided to publish these as [scoped packages](https://docs.npmjs.com/misc/scope). The scoped package concept is relatively new to npm and so will require npm version greater then 2.7.0 to use them. Checkout out the npm getting started guide for more info.

**Comment by grofit** [comment]
Yeah I had not seen anyone using that convention before, I understand the reasons behind using scoped packages (Especially on private repos), it just looks unsightly and verbose, but as long as it works I guess there are bigger fish to fry.

Thanks for taking the time out to let me know of the reasoning behind it though, will close the issue.
