### ISSUE TITLE
Can't properly link in folders content in pack()

### ISSUE THREAD

**Issue by yann-stepienik-cko** [OctopusDeploy/gulp-octo#7]
When trying to pass in the content of a folder using Gulp's classical SRC syntax : 

```
return gulp.src("./bin/**", {"base": "./bin/"})
    .pipe(octo.pack('zip'))
```

enven providing a "base" and/or "cwd" to it, gulp-octo will always use the root of the project as the basedir, therefore, if ./bin/assets exists, it will look for ./assets/ and output an error.

**Comment by aromine** [comment]
I had the same problem.  You can use process.chdir to change the working directory before running the pack.  That seems to work for a workaround:
```
gulp.task("Build-Package", function () {
    process.chdir(config.packageWorkingDir);
    
    return gulp.src(["./**"])
      .pipe(octo.pack())
      .pipe(gulp.dest(config.packageOutputPath));
});
```

**Comment by alxwest** [comment]
@zentron Your commit (9dc35278) of my fix also fixes this issue.

**Comment by zentron** [comment]
Thanks for the confirmation @alxwest
