### ISSUE TITLE
Package is always written to current working directory

### ISSUE THREAD

**Issue by svenschoenung** [OctopusDeploy/gulp-octo#8]
[Somebody on StackOverflow](http://stackoverflow.com/q/42655055/5892036) had a problem when trying to do what the documentation calls [a simple pack](https://github.com/OctopusDeploy/gulp-octo#simple-pack).

Basically no matter what is put in `gulp.dest()` the created package is always written to the current working directory.

I looked at the code and came up with the following explanation:

> It's a bug in `gulp-octo`. In [this line](https://github.com/OctopusDeploy/gulp-octo/blob/e08abdd/lib/pack.js#L31) they set the path of the generated archive. Unfortunately they just use the filename of the archive instead of a full path (which is [what they're supposed to do](https://github.com/gulpjs/vinyl#optionspath)), so the file is always written relative to the current working directory.

**Comment by micsco** [comment]
Bump this for a bit of attention. Is there someone at OctopusDeploy that can add this fix?

**Comment by zentron** [comment]
@micsco we have a pending CLA linked to in the PR that needs to be signed by @svenschoenung before we can perge the change
